# -*- coding: utf-8 -*-
"""DEC-GEN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188AyPg5U0X4Vqu7a2-Ks7jI380CXPg0k
"""

!pip install galois

import galois
import numpy as np

# --- CONFIGURATION ---
data_bits = 16         # Change to 16, 32, or 64
# ---------------------

# Defines for standard BCH codes
if data_bits == 16:
    n_mother, k_mother = 31, 21
    target_data = 16
    target_check = 10 # n=26
elif data_bits == 32:
    n_mother, k_mother = 63, 51
    target_data = 32
    target_check = 12 # n=44
elif data_bits == 64:
    n_mother, k_mother = 127, 113
    target_data = 64
    target_check = 14 # n=78

print(f"Generating Parity Matrix for Data={target_data}, Check={target_check}...")

# 1. Create the Mother Code Generator Matrix (G)
# G is typically returned as [I | P] or [P | I]. We need to ensure [I | P] form.
GF = galois.GF(2**(n_mother.bit_length() - 1))
bch = galois.BCH(n_mother, k_mother)
G_mother = bch.G # Shape (k_mother, n_mother)

# 2. Extract the Parity Part (P)
# galois.BCH usually creates systematic codes where G = [I | P]
# (Identity on the left, Parity on the right).
# Let's verify and extract P.
# We assume the columns k_mother to n_mother-1 are the parity columns.
P_mother = G_mother[:, k_mother:] # Shape (k_mother, r)

# 3. Shorten the Matrix
# We have 'k_mother' rows, but we only have 'target_data' bits.
# Shortening usually implies the "top" (first) bits are zero.
# So we keep the BOTTOM 'target_data' rows of the matrix.
rows_to_remove = k_mother - target_data
P_short = P_mother[rows_to_remove:, :] # Shape (target_data, target_check)

# 4. Generate Verilog Output
print("\n// --- COPY THIS INTO YOUR MODULE ---")
print(f"// Parity Matrix assignments for Data Width {target_data}")
print("initial begin")

for i in range(target_data):
    # Convert the row of 0s and 1s into an integer
    row_val = 0
    row_array = P_short[i, :] # Row i contains connections for Data Bit i

    for bit in row_array:
        row_val = (row_val << 1) | int(bit)

    # Verilog Indexing: P_matrix[0] corresponds to Data Bit 0 (LSB)
    # Python Matrix Indexing: Row 0 is usually MSB in poly arithmetic.
    # To match standard little-endian Verilog (Data[0]), we often read from the bottom up
    # or match the specific systematic layout.
    # For BCH, standard "High Order = Row 0".
    # If your Verilog data_i[0] is the LSB, we should map the Last Row of P to P_matrix[0].

    verilog_index = target_data - 1 - i
    print(f"    P_matrix[{verilog_index}] = {target_check}'h{row_val:03x};")

print("end")
print("// ----------------------------------")

import galois
import numpy as np

# -----------------------------------------------------------------------------
# Configuration: BCH (26, 16) derived from (31, 21)
# -----------------------------------------------------------------------------
n_mother = 31       # 2^5 - 1
k_mother = 21       # Standard BCH(31, 21) for t=2
n_target = 26       # Target codeword length
k_target = 16       # Target data length (shortened by 5)
t = 2               # Double Error Correcting

print(f"Generating Verilog cases for BCH({n_target}, {k_target})...")

# 1. Initialize Galois Field GF(2^5)
GF = galois.GF(2**5)

# 2. Create the Primitive BCH Code
# This generates the Generator Poly g(x) and Parity Check Matrix H
bch = galois.BCH(n_mother, k_mother)
H_mother = bch.H  # Shape is (10, 31)

# 3. Shorten the Code
# We shorten by removing the first (n_mother - n_target) columns.
# This corresponds to assuming the first 5 data bits are always 0.
shorten_by = n_mother - n_target
H_short = H_mother[:, shorten_by:]  # Shape becomes (10, 26)

# Convert H to standard integer array for easy processing
H_matrix = np.array(H_short, dtype=int)

# Helper function to calculate syndrome
def calculate_syndrome(error_vector, H):
    # Syndrome S = H * e^T (in GF2)
    # We perform matrix multiplication in GF2
    res = np.dot(H, error_vector) % 2
    # Convert binary array to integer
    syndrome_int = 0
    for bit in res:
        syndrome_int = (syndrome_int << 1) | int(bit)
    return syndrome_int

# -----------------------------------------------------------------------------
# Generate Verilog Case Statements
# -----------------------------------------------------------------------------
print("\n// --- BEGIN GENERATED VERILOG ---")
print("always_comb begin")
print("    error_pattern = '0;")
print("    double_error_o = 0;")
print("    if (error_detected_o) begin")
print("        case (syndrome)")

count = 0

# --- CASE 1: Single Bit Errors (26 cases) ---
for i in range(n_target):
    # Create error vector with 1 bit set
    e = np.zeros(n_target, dtype=int)
    e[n_target - 1 - i] = 1 # SystemVerilog index 0 is on the right

    syn = calculate_syndrome(e, H_matrix)

    # Format: 10'hXXX: error_pattern[i] = 1;
    print(f"            10'h{syn:03x}: error_pattern[{i}] = 1; // SBU at bit {i}")
    count += 1

# --- CASE 2: Double Bit Errors (325 cases) ---
for i in range(n_target):
    for j in range(i + 1, n_target):
        # Create error vector with 2 bits set
        e = np.zeros(n_target, dtype=int)
        e[n_target - 1 - i] = 1
        e[n_target - 1 - j] = 1

        syn = calculate_syndrome(e, H_matrix)

        # Format: 10'hXXX: begin error_pattern[i]=1; error_pattern[j]=1; end
        print(f"            10'h{syn:03x}: begin error_pattern[{i}] = 1; error_pattern[{j}] = 1; end // DBU at {i},{j}")
        count += 1

print("            default: begin")
print("                // Syndrome does not match 1 or 2 bit errors")
print("                // Likely >2 errors or logic upset")
print("                double_error_o = 1; // Flag as uncorrectable")
print("            end")
print("        endcase")
print("    end")
print("end")
print("// --- END GENERATED VERILOG ---")
print(f"\nTotal cases generated: {count}")

import galois
import numpy as np

##FIRST GOOD VERSION only 26 cases fail

# --- CONFIGURATION ---
n_mother, k_mother = 31, 21
target_data = 16
target_check = 10
total_width = 26

print(f"// Generating consistent logic for {target_data}-bit Data / {target_check}-bit Check")

# 1. Generate the Master P Matrix using Galois
GF = galois.GF(2**5)
bch = galois.BCH(n_mother, k_mother)
H_mother = bch.H
# Shorten
H_short = H_mother[:, n_mother - total_width:]
# Convert to integer array
H_int = np.array(H_short, dtype=int)

# 2. Extract the P Matrix values (Columns 0 to 15 of H correspond to Data)
# We treat the first 16 columns as Data, last 10 as Check.
# Note: In standard systematic form [Data | Check], Check part is Identity.
# We must ensure we grab the non-identity columns for the P-Matrix.
# For this specific library, usually the LAST columns are the identity (Check bits).
# Let's verify and extract.

P_values = []
print("\n    // 1. Paste this into 'initial begin' of Encoder AND Decoder")
print("    initial begin")
for i in range(target_data):
    # Get column from H matrix corresponding to this data bit
    # Data is at indices 0..15 in the codeword (H columns 0..15)
    col = H_int[:, i]

    # Convert column to integer
    val = 0
    for bit in col:
        val = (val << 1) | int(bit)

    P_values.append(val)

    # Verilog Index: Data 0 is at array index 0.
    # We map H-col 0 (Data MSB usually) to Data MSB or LSB?
    # Let's map H-col i to Data Bit (15-i) to keep MSB-first order
    v_index = target_data - 1 - i
    print(f"        P_matrix[{v_index}] = {target_check}'h{val:03x};")
print("    end")

# 3. Generate the Case Statement by SIMULATING the Verilog Hardware
# In your Verilog:
#   If Error in Check Bit 'i': Syndrome = (1 << i)
#   If Error in Data Bit 'j' : Syndrome = P_matrix[j]

syndrome_map = {} # Map syndrome -> Verilog String

# --- Single Bit Errors (SBU) ---
# Check Bits (0 to 9)
for i in range(target_check):
    syn = (1 << i) # Hardware logic forces this
    # Check bit 'i' is at Codeword index 'i'
    syndrome_map[syn] = f"error_pattern[{i}] = 1'b1; // Check Bit {i}"

# Data Bits (0 to 15) -> Codeword indices 10 to 25
for i in range(target_data):
    syn = P_values[target_data - 1 - i] # Retrieve the value we assigned to P_matrix[i]
    codeword_idx = i + target_check
    syndrome_map[syn] = f"error_pattern[{codeword_idx}] = 1'b1; // Data Bit {i}"

# --- Double Bit Errors (DBU) ---
# Iterate all pairs of codeword bits (0 to 25)
for i in range(total_width):
    for j in range(i + 1, total_width):
        # Calculate Syndrome A
        if i < target_check: syn_a = (1 << i)
        else: syn_a = P_values[target_data - 1 - (i - target_check)]

        # Calculate Syndrome B
        if j < target_check: syn_b = (1 << j)
        else: syn_b = P_values[target_data - 1 - (j - target_check)]

        # Total DBU Syndrome is XOR
        total_syn = syn_a ^ syn_b

        if total_syn in syndrome_map:
            # Collision! This means t=2 is not satisfied for this code definition.
            # But for BCH(26,16) it should be fine.
            pass
        else:
            syndrome_map[total_syn] = f"begin error_pattern[{i}] = 1'b1; error_pattern[{j}] = 1'b1; end"

# 4. Print Case Statement
print("\n    // 2. Paste this into 'bch_dec_decoder' Case Statement")
print("    case (syndrome)")
for syn, action in sorted(syndrome_map.items()):
    print(f"        10'h{syn:03x}: {action}")
print("        default: double_error_o = 1'b1;")
print("    endcase")

import galois
import numpy as np
##Working 100%

# --- CONFIGURATION: BCH(26, 16) ---
#n_mother, k_mother = 31, 21
#target_data = 16
#target_check = 10
#total_width = 26

# --- CONFIGURATION: BCH(44, 32) ---
#n_mother, k_mother = 63, 51   # Uses GF(2^6)
#target_data = 32
#target_check = 12             # 32 + 12 = 44
#total_width = 44

# --- CONFIGURATION: BCH(78, 64) ---
n_mother, k_mother = 127, 113 # Uses GF(2^7)
target_data = 64
target_check = 14             # 64 + 14 = 78
total_width = 78

print(f"// Generated for {target_data}-bit Data / {target_check}-bit Check")

# 1. Setup Code
GF = galois.GF(2**5)
bch = galois.BCH(n_mother, k_mother)

# 2. Extract P Matrix from the SYSTEMATIC Generator Matrix G = [I | P]
# This ensures P matches the systematic encoding used in Verilog
G = bch.G # dimensions [k_mother, n_mother]
# We want the last 'target_check' columns of G (The Parity Part)
# And the last 'target_data' rows (The Data Part we are using)
# Note: galois G usually puts I on the left, P on the right.
# We slice the bottom-right corner.
P_slice = G[k_mother - target_data :, k_mother :]

# Convert to simple integer list for logic generation
P_integers = []
print("\n// 1. PASTE THIS INTO 'bch_dec_encoder' AND 'bch_dec_decoder' (Initial Block)")
print("initial begin")
for i in range(target_data):
    # Convert row to integer
    row_val = 0
    row_vec = P_slice[i]
    for bit in row_vec:
        row_val = (row_val << 1) | int(bit)

    P_integers.append(row_val)

    # Map to Verilog: P_matrix[0] is LSB of Data.
    # In galois, last row is usually LSB of data.
    # Let's verify standard order: P_slice[last] -> Data[0]
    v_index = target_data - 1 - i
    print(f"    P_matrix[{v_index}] = {target_check}'h{row_val:03x};")
print("end")

# 3. Generate Case Statement using MATHEMATICAL LOGIC (Not Library)
# This forces the case statement to match the P_matrix perfectly.
# Logic:
#   Error in Check Bit k  -> Syndrome = (1 << k)
#   Error in Data Bit m   -> Syndrome = P_matrix[m]
#   Double Error          -> Syndrome = Syn(A) ^ Syn(B)

# Re-map P_integers to match Verilog Array Indexing
P_map = {} # Index -> Value
for i in range(target_data):
    v_index = target_data - 1 - i
    P_map[v_index] = P_integers[i]

syndrome_cases = {} # Syn -> Action String

# SBU: Check Bits (Verilog indices 0..9)
for i in range(target_check):
    syn = (1 << i)
    syndrome_cases[syn] = f"error_pattern[{i}] = 1'b1; // Check Bit {i}"

# SBU: Data Bits (Verilog indices 10..25)
for i in range(target_data):
    syn = P_map[i]
    cw_idx = i + target_check
    syndrome_cases[syn] = f"error_pattern[{cw_idx}] = 1'b1; // Data Bit {i}"

# DBU: All Pairs
for i in range(total_width):
    for j in range(i + 1, total_width):
        # Get Syn for bit i
        if i < target_check: syn_i = (1 << i)
        else: syn_i = P_map[i - target_check]

        # Get Syn for bit j
        if j < target_check: syn_j = (1 << j)
        else: syn_j = P_map[j - target_check]

        total_syn = syn_i ^ syn_j

        if total_syn not in syndrome_cases:
            syndrome_cases[total_syn] = f"begin error_pattern[{i}] = 1'b1; error_pattern[{j}] = 1'b1; end"

print("\n// 2. PASTE THIS INTO 'bch_dec_decoder' (Case Statement)")
print("case (syndrome)")
for syn in sorted(syndrome_cases.keys()):
    print(f"    {target_check}'h{syn:03x}: {syndrome_cases[syn]}")
print("    default: double_error_o = 1'b1;")
print("endcase")